print('>-<' * 20)
equipas = ('Benfica', 'Sporting', 'Boavista', 'Chaves', 'Braga', 'Porto', 'Rio Ave', 'São Martinho', 'Guimarães', 'Portimonense', 'Santa Clara', 'Moreirense', 'Arouca', 'Marítimo', 'Paços Ferreira', 'Nacional', 'Academica', 'Famalicão', 'Avintes', 'O. Douro')
print(f'Lista Equipas Primeira Liga: {equipas}')
print('>-<' * 20)
print(f'As primeiras 5 equipas são: {equipas[0:5]}')
print('>-<' * 20)
print(f'Os últimos 4 são: {equipas[-4:]}')
print('>-<' * 20)
print(f'Equipas por ordem alfabética: {sorted(equipas)}')
print('>-<' * 20)
print(f'O Braga está na posição {equipas.index("Braga") + 1}ª.')
